language: android
jdk: oraclejdk8
install: true
script: android create avd --force -n test -t android-17 --abi armeabi-v7a
        emulator -avd test -no-skin -no-audio -no-window
        gradle build
deploy:
  provider: heroku
  api_key: b3a40066-68cd-4421-8a3e-73e398287e69
